Release Cuba-3.0     http://www.feynarts.de/cuba/     Cuba-3.0.tar.gz [355 kB, MD5: dfd4297a3d9c8ef439fd0f2fba531152] (current version 3.0 beta)     last update: 24 Nov 11

diff --git a/tools/mcc b/tools/mcc
--- a/tools/mcc
+++ b/tools/mcc
@@ -2,7 +2,7 @@
 # this script jumps in if there is no working mcc on the path:
 # - on Mac OS it (hopefully) figures out the location of mcc,
 # - on Cygwin it substitutes mcc completely
-# last modified 2 Feb 11 th
+# last modified 19 Jul 11 th
 
 
 sdkpath()
@@ -17,18 +17,21 @@ sdkpath()
     Print["topdir=\"", $TopDirectory, "\""];
     Exit[]' < /dev/null | tr '\r' ' ' | tail -2`
 
-	# Cygwin's dlltool does not handle native 64-bit libraries yet
-  [ "$sysid" = Windows-x86-64 ] && sysid=Windows
+	# check whether Cygwin's dlltool can handle 64-bit DLLs
+  test "$sysid" = Windows-x86-64 && {
+    ${DLLTOOL:-dlltool} --help | grep x86-64 > /dev/null || sysid=Windows
+  }
+
   topdir=`cd "$topdir" ; echo $PWD`
 
   for sdk in \
-    "$topdir/AddOns/MathLink/DeveloperKit/$sysid/CompilerAdditions" \
     "$topdir/SystemFiles/Links/MathLink/DeveloperKit/$sysid/CompilerAdditions" \
-    "$topdir/SystemFiles/Links/MathLink/DeveloperKit/CompilerAdditions" ; do
-    [ -d "$sdk" ] && return
+    "$topdir/SystemFiles/Links/MathLink/DeveloperKit/CompilerAdditions" \
+    "$topdir/AddOns/MathLink/DeveloperKit/$sysid/CompilerAdditions" ; do
+    test -d "$sdk" && return
   done
 
-  echo "Cannot determine Mathematica's system ID using $mathcmd" 1>&2
+  echo "MathLink SDK not found" 1>&2
   exit 1
 }
 
@@ -36,74 +39,77 @@ sdkpath()
 cygmcc()
 {
   sdkpath math \
-    "`cygpath \"$ProgramW6432\"`/Wolfram Research/Mathematica"/* \
-    "`cygpath \"$PROGRAMFILES\"`/Wolfram Research/Mathematica"/*
+    "`cygpath '$ProgramW6432'`/Wolfram Research/Mathematica"/* \
+    "`cygpath '$PROGRAMFILES'`/Wolfram Research/Mathematica"/*
+
   for sdk in "$sdk"/m* ; do
     break
   done
 
-  [ `basename "$sdk"` = cygwin ] && {
-    CC=${CC:-gcc} bash -O igncr "$sdk/bin/mcc" "$@"
-    return
-  }
-
   cache=MLcyg-cache
-  [ -d $cache ] || mkdir $cache
+  test -d $cache || mkdir $cache
 
   MLversion=3
   for OSbits in 32 64 ; do
     dllname=ml${OSbits}i$MLversion
     libname="$sdk/lib/${dllname}m.lib"
-    [ -f "$libname" ] && break
+    test -f "$libname" && break
   done
 
   lib="$cache/${dllname}m"
-  [ -f "$lib.a" ] || {
+  test -f "$lib.a" || {
     ( echo "EXPORTS"
-      nm -C --defined-only "$libname" | awk '/ T [^.]/ { print $3 }' ) > "$lib.def"
-    dlltool --dllname "$dllname.dll" --def "$lib.def" --output-lib "$lib.a" -k
+      ${NM:-nm} -C --defined-only "$libname" | awk '/ T [^.]/ { print $3 }'
+    ) > "$lib.def"
+    ${DLLTOOL:-dlltool} -k --dllname "$dllname.dll" \
+      --def "$lib.def" --output-lib "$lib.a"
   }
 
+  tmp=
+  args="-DWIN$OSbits -I'$sdk/include'"
   for arg in "$@" ; do
     case "$arg" in
-    -l* | -L* | *.a)
-	ldflags="$ldflags $arg" ;;
     *.tm)
 	cp "$arg" "$arg.tm"
 	"$sdk"/bin/mprep -lines -o "$arg.c" "$arg.tm"
-	tmp="$tmp $arg.c $arg.tm"
-	ccflags="$ccflags $arg.c" ;;
+	tmp="$tmp '$arg.c' '$arg.tm'"
+	args="$args '$arg.c'" ;;
     *)
-	ccflags="$ccflags $arg" ;;
+	args="$args '$arg'" ;;
     esac
   done
 
   trap "rm -f $tmp" 0 1 2 3 15
-
-  set -x
-  ${CC:-gcc} -DWIN$OSbits -I"$sdk/include" $ccflags $ldflags $lib.a -mwindows
+  eval "set -x ; ${CC:-gcc} $args $lib.a -mwindows"
 }
 
 
 macmcc()
 {
-  sdkpath MathKernel /Applications/Mathematica*/Contents/MacOS \
-                     $HOME/Desktop/Mathematica*/Contents/MacOS
-
-  "$sdk/mcc" "$@" && exit 0
-
-  echo "mcc not found"
+  sdkpath MathKernel \
+    /Applications/Mathematica*/Contents/MacOS \
+    $HOME/Desktop/Mathematica*/Contents/MacOS
+  exec "$sdk/mcc" "$@"
 }
 
+
+defaultmcc()
+{
+  sdkpath math \
+    /usr/local/bin \
+    /usr/local/Wolfram/bin \
+    /usr/local/Wolfram/Mathematica/*/Executables \
+    /opt/Wolfram/bin \
+    /opt/Wolfram/Mathematica/*/Executables
+  exec "$sdk/mcc" "$@"
+}
 
 
 shopt -s nullglob 2> /dev/null
 
-ostype=`uname -s`
-
-case $ostype in
+case `uname -s` in
 Darwin) macmcc "$@" ;;
 CYG*)   cygmcc "$@" ;;
-*)      echo "Unknown OS $ostype" 1>&2 ;;
+*)      defaultmcc "$@" ;;
 esac
 
