Release Cuba-1.4

diff --git a/tools/mcc b/tools/mcc
--- a/tools/mcc
+++ b/tools/mcc
@@ -2,8 +2,7 @@
 # this script jumps in if there is no working mcc on the path:
 # - on Mac OS it (hopefully) figures out the location of mcc,
 # - on Cygwin it substitutes mcc completely
-# this file is part of FeynHiggs
-# last modified 29 Jun 07 th
+# last modified 8 Nov 07 th
 
 
 sdkpath()
@@ -11,18 +10,22 @@ sdkpath()
   mathcmd="$1"
   shift
 
-  for dir in "$@" ; do
-    path="$dir:$path"
+  for sdk in "$@" ; do
+    path="$sdk:$path"
   done
+  mathcmd="`PATH=\"$PATH:$path\" which $mathcmd`"
   
-  sdk=`PATH="$PATH:$path" "$mathcmd" << \_EOF_ | tail -1
-	WriteString["stdout", "\n" <>
-	  ToFileName[{$TopDirectory, "AddOns", "MathLink",
-	    "DeveloperKit", $SystemID, "CompilerAdditions"}]]; Exit[]
-_EOF_`
-  [ -z "$sdk" ] || return
+  read -r sysid topdir <<< `$mathcmd -run \
+    'Print[$SystemID, " ", $TopDirectory]; Exit[]' < /dev/null | tr '\r' ' ' | tail -1`
 
-  echo "Cannot determine system type" 1>&2
+  for sdk in \
+    "$topdir/AddOns/MathLink/DeveloperKit/$sysid/CompilerAdditions" \
+    "$topdir/SystemFiles/Links/MathLink/DeveloperKit/$sysid/CompilerAdditions" \
+    "$topdir/SystemFiles/Links/MathLink/DeveloperKit/CompilerAdditions" ; do
+    [ -d "$sdk" ] && return
+  done
+
+  echo "Cannot determine Mathematica's system ID using $mathcmd" 1>&2
   exit 1
 }
 
@@ -30,15 +33,20 @@ _EOF_`
 cygmcc()
 {
   sdkpath math "$PROGRAMFILES/Wolfram Research/Mathematica"/*
-  for sdk in "$sdk"/* ; do
+  for sdk in "`cd \"$sdk\" ; pwd`"/m* ; do
     break
   done
+
+  [ `basename "$sdk"` = cygwin ] && {
+    CC=${CC:-gcc} bash -O igncr "$sdk/bin/mcc" "$@"
+    return
+  }
 
   cache=MLcyg-cache
   [ -d $cache ] || mkdir $cache
 
   OSbits=32
-  MLversion=1
+  MLversion=3
 
   dllname=ml${OSbits}i$MLversion
   libname="$sdk/lib/${dllname}m.lib"
